### ISSUE TITLE
GridFace source Code

### ISSUE THREAD

**Issue by kao123** [ShownX/FacePaperCollection#1]
Hi, 
the paper collection is really great.. i was wondering if there're any implementation of :GridFace: Face Rectification via Learning Local Homography Transformations, I'm in an urgent need for it 
Thank you

**Comment by ShownX** [comment]
Hi, kao123,

Sorry for late response. I cannot find the source code for that paper either. If the authors publish the code, I will update this repository. Any face research/engineer related merge request is welcome.

**Comment by MyraBaba** [comment]
@ShownX 

any update on this?
